CREATE USER IF NOT EXISTS 'cmdbd'@'%' IDENTIFIED BY PASSWORD '*827FDBE6EA30E5FB96D2573FB10EF1B3F49247A2';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'cmdbd'@'%';
GRANT SELECT, INSERT, UPDATE, LOCK TABLES, DELETE, EXECUTE  ON `gocmdb`.* TO 'cmdbd'@'%';
